### PR TITLE
Useful commits for any git repo

### PR DESCRIPTION
**Pull request by Elte156**
This fixes issue #1

### CODE REVIEW

**Comment by Elte156** [comment]
I don't have a webcam on my main dev machine to test, but I was able to see the request come through on `chrome://webrtc-internals/`

**Review by seanpcook — APPROVED** [review]
You're smart

**Comment by seanpcook** [comment]
@Elte156 It's telling me there is a security vulnerability with minimist version in the lockfile and wants me to update to 0.2.1

**Comment by Elte156** [comment]
What is `it`?

You can post the console messages here.

**Comment by seanpcook** [comment]
Screen Shot 2020-04-30 at 19 24 25

**Comment by Elte156** [comment]
Alright add that line of code to your package.json file.
Then run `npm update`

Then commit the new `package.json` and `package-lock.json` file

**Pull request merged**
